const patientsDetails = [
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
  {
    ilnesses: [
      {
        name: 'Blood',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'Colon',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
      {
        name: 'heart disease(right ventricle)',
        doctors: [
          {
            name: 'Emily Parker',
            treatment: 'Colon',
            type: 'Chimical',
            details: '50%',
          },
          {
            name: 'Harper Patel',
            treatment: 'Blood',
            type: 'Sergury',
            details: '70%',
          },
          {
            name: 'Lucas McCall',
            treatment: 'Prostat',
            type: 'Harmony',
            details: '20%',
          },
        ],
        charities: [
          { name: 'Hayat', typePayment: 'Treatment', percent: '49.95' },
          { name: 'Sama', typePayment: 'Testing', percent: '30.04' },
          { name: 'Barakat', typePayment: 'Room', percent: '20.01' },
        ],
      },
    ],
    data: [
      {
        year: '1994',
        Colon: 2,
        Blood: 0,
        Prostat: 1,
      },
      {
        year: '1995',
        Colon: 2.1,
        Blood: 0.4,
        Prostat: 1.1,
      },
      {
        year: '1996',
        Colon: 2.2,
        Blood: 0.5,
        Prostat: 1,
      },
      {
        year: '1997',
        Colon: 2.3,
        Blood: 0.7,
        Prostat: 0.6,
      },
      {
        year: '1998',
        Colon: 2.2,
        Blood: 1,
        Prostat: 0.3,
      },
      {
        year: '1999',
        Colon: 2,
        Blood: 1.2,
        Prostat: 0.3,
      },
      {
        year: '2000',
        Colon: 2.2,
        Blood: 0.9,
        Prostat: 0.4,
      },
      {
        year: '2001',
        Colon: 2.5,
        Blood: 0.5,
        Prostat: 0.7,
      },
      {
        year: '2002',
        Colon: 2.8,
        Blood: -0.1,
        Prostat: 1,
      },
      {
        year: '2003',
        Colon: 3,
        Blood: -0.4,
        Prostat: 1.2,
      },
      {
        year: '2004',
        Colon: 3.5,
        Blood: -1,
        Prostat: 1.2,
      },
      {
        year: '2005',
        Colon: 3.4,
        Blood: -1,
        Prostat: 1.5,
      },
      {
        year: '2006',
        Colon: 3,
        Blood: -0.7,
        Prostat: 0.9,
      },
      {
        year: '2007',
        Colon: 2,
        Blood: 0.1,
        Prostat: 1.5,
      },
      {
        year: '2008',
        Colon: 1.5,
        Blood: 0.4,
        Prostat: 2.1,
      },
      {
        year: '2009',
        Colon: 1.6,
        Blood: 0,
        Prostat: 1.9,
      },
      {
        year: '2010',
        Colon: 1.7,
        Blood: -0.2,
        Prostat: 1.5,
      },
      {
        year: '2011',
        Colon: 1.2,
        Blood: 0.3,
        Prostat: 0.8,
      },
      {
        year: '2012',
        Colon: 1,
        Blood: 0.5,
        Prostat: 0.8,
      },
    ],
  },
];
export default patientsDetails;
